[package]
name = "foundationdb"
version = "0.3.0"
authors = ["Benjamin Fry <benjaminfry@me.com>"]

description = """
High level client bindings for FoundationDB.
"""

documentation = "https://docs.rs/foundationdb"
repository = "https://github.com/bluejekyll/foundationdb-rs"
license = "MIT/Apache-2.0"

readme = "README.md"
keywords = ["foundationdb", "kv"]
categories = ["database"]

[badges]
travis-ci = { repository = "bluejekyll/foundationdb-rs" }
# codecov = { repository = "bluejekyll/foundationdb-rs", branch = "master", service = "github" }

[features]
default = ["fdb-6_1", "uuid"]

fdb-5_1 = [ "foundationdb-sys/fdb-5_1" ]
fdb-5_2 = [ "foundationdb-sys/fdb-5_2" ]
fdb-6_0 = [ "foundationdb-sys/fdb-6_0" ]
fdb-6_1 = [ "foundationdb-sys/fdb-6_1" ]

[build-dependencies]
foundationdb-gen = { version = "0.1.0", path = "../foundationdb-gen" }

[dependencies]
failure = "0.1"
failure_derive = "0.1"
foundationdb-sys = { version = "0.2.0", path = "../foundationdb-sys", default-features = false }
futures = "0.1"
lazy_static = "1.0"
byteorder = "1.2"
log = "0.4"
uuid = { version = "0.7", optional = true }
rand = "0.7.0"

[dev-dependencies]
rand = "0.7"
