[package]
name = "foundationdb"
version = "0.4.0"
authors = ["Benjamin Fry <benjaminfry@me.com>"]
edition = "2018"

description = """
High level client bindings for FoundationDB.
"""

documentation = "https://docs.rs/foundationdb"
repository = "https://github.com/bluejekyll/foundationdb-rs"
license = "MIT/Apache-2.0"

readme = "README.md"
keywords = ["foundationdb", "kv"]
categories = ["database"]

[badges]
travis-ci = { repository = "bluejekyll/foundationdb-rs" }
# codecov = { repository = "bluejekyll/foundationdb-rs", branch = "master", service = "github" }

[features]
default = ["fdb-6_1", "uuid"]

fdb-5_1 = [ "foundationdb-sys/fdb-5_1" ]
fdb-5_2 = [ "foundationdb-sys/fdb-5_2" ]
fdb-6_0 = [ "foundationdb-sys/fdb-6_0" ]
fdb-6_1 = [ "foundationdb-sys/fdb-6_1" ]
fdb-6_2 = [ "foundationdb-sys/fdb-6_2" ]

[build-dependencies]
foundationdb-gen = { path = "../foundationdb-gen" }

[dependencies]
failure = "0.1"
failure_derive = "0.1"
foundationdb-sys = { version = "0.2.0", path = "../foundationdb-sys", default-features = false }
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }
memchr = "2.2.1"
static_assertions = "1.0.0"
uuid = { version = "0.8.1", optional = true }

[dev-dependencies]
byteorder = "1.2"
lazy_static = "1.0"
log = "0.4"
rand = "0.6"
